# Generated by Django 4.1.6 on 2023-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Email',
            new_name='email',
        ),
    ]
